apiVersion: apps/v1
kind: Deployment
metadata:
  name: street-view
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - image: 12345678hacker/ant_view:latest
          name: django
          ports:
            - containerPort: 8080
              name: gunicorn