---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: street-view
  labels:
    app: street-view
spec:
  replicas: 1
  selector:
    matchLabels:
      app: street-view
  template:
    metadata:
      labels:
        app: street-view
    spec:
      containers:
        - image: 12345678hacker/street-view:1.0.0
          name: street-view
          ports:
            - containerPort: 8080
              name: gunicorn

---

apiVersion: v1
kind: Service
metadata:
  name: street-service
  labels:
    app: street-view
spec:
  type: NodePort
  selector:
    app: street-view
  ports:
    - port: 8080